language: java
jdk: oraclejdk8
branches:
  except:
    - /^b[0-9]/
before_install:
  - sh gradlew clean
install:
  - sh gradlew setupCIWorkspace --continue
script:
  - sh gradlew build --continue
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  - provider: script
    skip_cleanup: true
# ready to CurseForge, Bintray
#    script: "sh gradlew githubRelease bintrayUpload curseforge --continue"
    script: "sh gradlew githubRelease --continue"
    on:
      all_branches: true
      condition: '! "$TRAVIS_BRANCH" =~ ^(dev\\-|feature\\/).*$'
notifications:
  email: false
  webhooks:
    urls:
      secure: ""